### ISSUE TITLE
What do you need help with?

### ISSUE THREAD

**Issue by SenorFusion** [Roastero/Roastero#1]
Hey guys,

Just found your project - Thanks for the awesome work you are doing! My dad and I are having a blast learning to the roast with SR700. He's in the Facebook group - that's how I heard about Roastero. He's super-pumped to be test driving.

Just wanted to drop by and ask: 

Are you looking for help on the project?
If so, How can we help?

Thanks!

**Comment by lodge93** [comment]
Hi SenorFusion!

We would love some help on the project! If you are interested in adding features to the program, we would be more than willing to help you set up a development environment. We have the process documented in our readme but there always seems to be some dependency that gives me trouble even when following our own documentation. If you find bugs, feel free to add them to our issue tracker so we are aware of them. If you would like to write either user documentation or developer documentation, that would also be greatly appreciated! Let me know what your interests/abilities are and we will surely get you involved in the project wherever you feel comfortable!

-Mark

**Comment by SenorFusion** [comment]
Hey Mark,

I followed your dev environment instructions for Ubuntu and Roastero fired right up. numpy took a looooong time to install but otherwise good to go I think.

I'm in digital marketing and some web development - so I won't be much help adding features, but I can definitely work on the User Documentation, Roaster-Web, and probably some of the Qt/GUI styling.

I'll watch the issues and jump in where I can.

**Comment by lodge93** [comment]
Sounds great! I remember the last time I ran Roastero on Ubuntu there was an orange focus ring on the tab that wasn't selected on the main bar. If you are still interested in helping, removing the highlight and cleaning up any additional graphical issues for Ubuntu would be awesome!
